//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.BooksAtHome
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Book.
    /// </summary>
    //  *** Start programmer edit section *** (Book CustomAttributes)

    //  *** End programmer edit section *** (Book CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookE", new string[] {
            "Name as \'Name\'",
            "Year as \'Year\'",
            "DateOfBuy as \'Date of buy\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'",
            "Language as \'Language\'",
            "Language.Name as \'Name\'"}, Hidden=new string[] {
            "Author.Name",
            "Language.Name"})]
    [AssociatedDetailViewAttribute("BookE", "Tags", "TagE", true, "", "Tags", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("BookE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [MasterViewDefineAttribute("BookE", "Language", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("BookL", new string[] {
            "Name as \'Name\'",
            "Year as \'Year\'",
            "DateOfBuy as \'Date of buy\'",
            "Author.Name as \'Name\'",
            "Language.Name as \'Name\'"})]
    public class Book : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private int fYear;
        
        private System.DateTime fDateOfBuy;
        
        private IIS.BooksAtHome.Author fAuthor;
        
        private IIS.BooksAtHome.Language fLanguage;
        
        private IIS.BooksAtHome.DetailArrayOfTag fTags;
        
        //  *** Start programmer edit section *** (Book CustomMembers)

        //  *** End programmer edit section *** (Book CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Name CustomAttributes)

        //  *** End programmer edit section *** (Book.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Name Get start)

                //  *** End programmer edit section *** (Book.Name Get start)
                string result = this.fName;
                //  *** Start programmer edit section *** (Book.Name Get end)

                //  *** End programmer edit section *** (Book.Name Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Name Set start)

                //  *** End programmer edit section *** (Book.Name Set start)
                this.fName = value;
                //  *** Start programmer edit section *** (Book.Name Set end)

                //  *** End programmer edit section *** (Book.Name Set end)
            }
        }
        
        /// <summary>
        /// Year.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Year CustomAttributes)

        //  *** End programmer edit section *** (Book.Year CustomAttributes)
        public virtual int Year
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Year Get start)

                //  *** End programmer edit section *** (Book.Year Get start)
                int result = this.fYear;
                //  *** Start programmer edit section *** (Book.Year Get end)

                //  *** End programmer edit section *** (Book.Year Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Year Set start)

                //  *** End programmer edit section *** (Book.Year Set start)
                this.fYear = value;
                //  *** Start programmer edit section *** (Book.Year Set end)

                //  *** End programmer edit section *** (Book.Year Set end)
            }
        }
        
        /// <summary>
        /// DateOfBuy.
        /// </summary>
        //  *** Start programmer edit section *** (Book.DateOfBuy CustomAttributes)

        //  *** End programmer edit section *** (Book.DateOfBuy CustomAttributes)
        public virtual System.DateTime DateOfBuy
        {
            get
            {
                //  *** Start programmer edit section *** (Book.DateOfBuy Get start)

                //  *** End programmer edit section *** (Book.DateOfBuy Get start)
                System.DateTime result = this.fDateOfBuy;
                //  *** Start programmer edit section *** (Book.DateOfBuy Get end)

                //  *** End programmer edit section *** (Book.DateOfBuy Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.DateOfBuy Set start)

                //  *** End programmer edit section *** (Book.DateOfBuy Set start)
                this.fDateOfBuy = value;
                //  *** Start programmer edit section *** (Book.DateOfBuy Set end)

                //  *** End programmer edit section *** (Book.DateOfBuy Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Author CustomAttributes)

        //  *** End programmer edit section *** (Book.Author CustomAttributes)
        [NotNull()]
        public virtual IIS.BooksAtHome.Author Author
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Author Get start)

                //  *** End programmer edit section *** (Book.Author Get start)
                IIS.BooksAtHome.Author result = this.fAuthor;
                //  *** Start programmer edit section *** (Book.Author Get end)

                //  *** End programmer edit section *** (Book.Author Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Author Set start)

                //  *** End programmer edit section *** (Book.Author Set start)
                this.fAuthor = value;
                //  *** Start programmer edit section *** (Book.Author Set end)

                //  *** End programmer edit section *** (Book.Author Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Language CustomAttributes)

        //  *** End programmer edit section *** (Book.Language CustomAttributes)
        public virtual IIS.BooksAtHome.Language Language
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Language Get start)

                //  *** End programmer edit section *** (Book.Language Get start)
                IIS.BooksAtHome.Language result = this.fLanguage;
                //  *** Start programmer edit section *** (Book.Language Get end)

                //  *** End programmer edit section *** (Book.Language Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Language Set start)

                //  *** End programmer edit section *** (Book.Language Set start)
                this.fLanguage = value;
                //  *** Start programmer edit section *** (Book.Language Set end)

                //  *** End programmer edit section *** (Book.Language Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        //  *** Start programmer edit section *** (Book.Tags CustomAttributes)

        //  *** End programmer edit section *** (Book.Tags CustomAttributes)
        public virtual IIS.BooksAtHome.DetailArrayOfTag Tags
        {
            get
            {
                //  *** Start programmer edit section *** (Book.Tags Get start)

                //  *** End programmer edit section *** (Book.Tags Get start)
                if ((this.fTags == null))
                {
                    this.fTags = new IIS.BooksAtHome.DetailArrayOfTag(this);
                }
                IIS.BooksAtHome.DetailArrayOfTag result = this.fTags;
                //  *** Start programmer edit section *** (Book.Tags Get end)

                //  *** End programmer edit section *** (Book.Tags Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Book.Tags Set start)

                //  *** End programmer edit section *** (Book.Tags Set start)
                this.fTags = value;
                //  *** Start programmer edit section *** (Book.Tags Set end)

                //  *** End programmer edit section *** (Book.Tags Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookE", typeof(IIS.BooksAtHome.Book));
                }
            }
            
            /// <summary>
            /// "BookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookL", typeof(IIS.BooksAtHome.Book));
                }
            }
        }
    }
}
